"""Identifier types and generators.

These ``NewType`` aliases only distinguish semantics during static checking;
at runtime they are just ``str`` / ``int``. Generators are centralized here to
keep the prefix format consistent between the Gateway and worker sides.
"""

from __future__ import annotations

import uuid
from typing import NewType

__all__ = [
    "BindingToken",
    "EpisodeId",
    "OperationSeq",
    "RequestId",
    "SessionId",
    "new_binding_token",
    "new_request_id",
    "new_session_id",
]

SessionId = NewType("SessionId", str)
"""``"sess-<uuid4hex>"``, generated by the Gateway."""

RequestId = NewType("RequestId", str)
"""Generated by the caller, used for operation idempotency."""

BindingToken = NewType("BindingToken", str)
"""An opaque binding identifier generated by the EnvWorker; the old token is
invalidated immediately once the slot is released and reused."""

EpisodeId = NewType("EpisodeId", int)
"""Incremented on every successful reset, starting from 1."""

OperationSeq = NewType("OperationSeq", int)
"""Incremented per state-changing operation within a session, starting from 1."""


def new_session_id() -> SessionId:
    """Generate a new session identifier.

    Returns:
        An identifier of the form ``sess-<uuid4hex>``.
    """
    return SessionId(f"sess-{uuid.uuid4().hex}")


def new_request_id() -> RequestId:
    """Generate a new request identifier (used when the caller does not
    provide one).

    Returns:
        An identifier of the form ``req-<uuid4hex>``.
    """
    return RequestId(f"req-{uuid.uuid4().hex}")


def new_binding_token() -> BindingToken:
    """Generate a new binding token (used on the EnvWorker side).

    Returns:
        An opaque identifier of the form ``bind-<uuid4hex>``.
    """
    return BindingToken(f"bind-{uuid.uuid4().hex}")
